/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

void fib(long int n)
{
   long int a=1,b=2,c,result=2;
    while(result<n)
    {
        c=a+b;
        a=b;
        b=c;
        if(c%2==0)
        result+=c;
    }
    cout<<result;
    
}

int main()
{
    fib(4000000);
    return 0;
}
